//  GPIO
#define BUTTON GPIO_NUM_0
#define SCL_PIN GPIO_NUM_13
#define SDA_PIN GPIO_NUM_12
#define LED_PIN GPIO_NUM_6

//  MYAM_LED_COLORS
#define CO2_THRES_DANGER 1600 
#define CO2_THRES_WARN 1000

// LED
#define LED_BRIGHTNESS_PERCENT 10
#define LED_BLINK_DELAY_MS 250

// MEASUREMENT
#define STCC4_MEASUREMENT_INTERVAL_MS 1500 

// NO_ERROR
#ifdef NO_ERROR
#undef NO_ERROR
#endif
#define NO_ERROR 0

// BLE
#define BLE_DEFAULT_DEVICE_NAME "OpenCO2-Mini"